version: 'Build {build}'
image: Visual Studio 2019
skip_branch_with_pr: true

services:
  - mongodb
install:
  - choco install Memurai-Developer
  
build_script:
  - ps: dotnet restore
  - ps: dotnet build --no-restore -c Release
  - ps: dotnet test --no-restore /p:SkipBuildVersioning=true
  - ps: dotnet pack --no-build -c Release /p:PackageOutputPath=build-artifacts

test: false
artifacts:
  - path: '**\build-artifacts\*'
